name: fetch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'  # 每3天运行一次 (UTC时间)

jobs:
  fetchurl:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2小时超时
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.5.0'
        cache: 'npm'
    
    - name: Install and configure SSH for Gitee
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITEE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
    
    - name: Configure Git for large repositories
      run: |
        git config --global http.postBuffer 524288000
        git config --global core.compression 9
        
    - name: Clone migu_video repository via SSH
      run: git clone git@gitee.com:dream-deve/migu_video.git
      
    - name: Set npm registry
      run: npm config set registry https://registry.npmmirror.com
      working-directory: ./migu_video
      
    - name: Install dependencies and run script
      run: npm install && node fetchURLByAndroidV2.js
      working-directory: ./migu_video
      
    - name: Configure git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
      working-directory: ./migu_video
      
    - name: Commit changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update by GitHub Actions"
      working-directory: ./migu_video
      
    - name: Push changes back to Gitee
      run: git push origin main
      working-directory: ./migu_video
